import Navbar from '@/components/Navbar'
import './globals.css'
import { Inter } from 'next/font/google'
import { Noto_Kufi_Arabic } from 'next/font/google'
const inter = Inter({ subsets: ['latin'] })
const noto=Noto_Kufi_Arabic({subsets:['arabic']})
export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
    
      <body className={noto.className}>
      <Navbar/>
        {children}
        </body>
    </html>
  )
}
